"""
GasUp Connector — Fase 2

Abstract interface for consuming GasUp transaction data in the Central Gas
AI Agent (retention engine, market intelligence, operational dashboards).

Data flows INTO this connector from two sources:
  1. Fly.io webhook server (gasup-webhook.ts) forwards transactions
  2. Local file watcher picks up Excel reports dropped in a folder

Data flows OUT to:
  - retention engine (build_client_profiles, alert on inactivity)
  - market_loader (enrich vehicle profiles with real consumption)
  - operational dashboards (station utilization, revenue tracking)

Architecture:
  GasUp BackOffice
    → gasup-webhook.ts (Fly.io) → Airtable TABLE_RECAUDO (financial engine)
    → gasup_connector.py (this) → retention engine (central-gas-agent)

The connector is source-agnostic: it consumes GasUpTransaction objects
regardless of whether they came from a webhook, Excel upload, or CSV.

Integration with market_loader.py:
  - classify_placa() identifies the vehicle segment
  - SEGMENT_PARAMS provides expected consumption for anomaly detection
  - build_existing_profiles() can be enriched with real GasUp data
"""

from __future__ import annotations

import csv
import hashlib
import json
import logging
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from decimal import Decimal
from enum import Enum
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)


# ============================================================
# Data Models
# ============================================================

@dataclass
class GasUpTransaction:
    """Single fuel transaction from GasUp BackOffice."""
    placa: str                          # Vehicle plate (uppercase, no spaces)
    litros: float                       # LEQ dispensed
    precio_unitario: float              # Price per LEQ (base)
    total: float                        # Total charged
    estacion_id: str                    # Station ID (e.g., "ECG-01")
    estacion_nombre: str                # Station name
    manguera: int                       # Dispenser hose (1-8)
    fecha_hora: datetime                # Transaction timestamp
    medio_pago: str                     # "efectivo" | "credito" | "prepago" | "tarjeta"
    ticket_id: str                      # Unique receipt number

    # Optional enrichment
    sobreprecio: float = 0.0            # Surcharge per LEQ (financing)
    total_sobreprecio: float = 0.0      # litros × sobreprecio
    turno: str = ""
    promotor: str = ""
    chip_id: str = ""
    forma_pago: str = ""                # "contado" | "credito" | "prepago"
    id_cliente: str = ""
    nombre_cliente: str = ""


@dataclass
class DailyClose:
    """Daily close summary for a station."""
    estacion_id: str
    fecha: str                          # YYYY-MM-DD
    total_litros: float
    total_ventas_mxn: float
    total_transacciones: int
    ventas_por_medio_pago: dict[str, float] = field(default_factory=dict)
    ventas_por_turno: dict[str, float] = field(default_factory=dict)
    mangueras_activas: int = 0


@dataclass
class VehicleConsumption:
    """Aggregated consumption for a single vehicle (for retention)."""
    placa: str
    total_litros: float
    total_cargas: int
    total_mxn: float
    total_sobreprecio: float            # Total accumulated toward financing
    primera_carga: datetime | None = None
    ultima_carga: datetime | None = None
    estaciones: set[str] = field(default_factory=set)
    litros_promedio_por_carga: float = 0.0
    dias_sin_cargar: int = 0


class AlertType(str, Enum):
    """Retention alert types triggered by GasUp data."""
    INACTIVITY = "INACTIVITY"           # No carga in X days
    CONSUMPTION_DROP = "CONSUMPTION_DROP"  # Volume dropped significantly
    CHURN_RISK = "CHURN_RISK"           # Pattern suggests switching to competitor
    NEW_VEHICLE = "NEW_VEHICLE"         # First-time vehicle at our station
    HIGH_VALUE = "HIGH_VALUE"           # Above-average consumption (VIP treatment)


@dataclass
class RetentionAlert:
    """Alert generated by comparing GasUp data against expected patterns."""
    placa: str
    alert_type: AlertType
    severity: str                       # "low" | "medium" | "high" | "critical"
    message: str
    data: dict = field(default_factory=dict)
    created_at: datetime = field(default_factory=datetime.now)


# ============================================================
# GasUp Connector (abstract interface)
# ============================================================

class GasUpConnector:
    """
    Central interface for GasUp data consumption.

    Maintains an in-memory transaction log and vehicle consumption
    aggregates. In production, backs to Neon PostgreSQL or Airtable.

    Usage:
        connector = GasUpConnector()
        connector.ingest_transaction(tx)        # from webhook
        connector.ingest_excel_report(path)     # from file watcher
        alerts = connector.check_retention()     # periodic check
        profile = connector.get_vehicle(placa)   # for retention engine
    """

    def __init__(self):
        # Sobreprecio is VARIABLE ($2-$14+/LEQ) — never use a default.
        # It comes from the recaudos_financiera report or webhook payload.
        self._transactions: list[GasUpTransaction] = []
        self._vehicles: dict[str, VehicleConsumption] = {}
        self._processed_tickets: set[str] = set()
        self._daily_closes: dict[str, DailyClose] = {}  # key: "estacion:YYYY-MM-DD"

        # Retention thresholds (from market_loader SEGMENT_PARAMS)
        self._inactivity_days: dict[str, int] = {
            "COMBI": 3,     # Combis load daily — 3 days = alarm
            "TAXI": 5,      # Taxis load every 2-3 days
            "PLATAFORMA": 5,
            "TP": 7,        # TP loads weekly
            "BUS": 3,       # Buses load daily (large volume)
            "PARTICULAR": 14,
            "UNKNOWN": 7,
        }

    # ── Ingestion ──────────────────────────────────────────────

    def ingest_transaction(self, tx: GasUpTransaction) -> bool:
        """
        Ingest a single transaction. Returns False if duplicate.

        Called by:
          - Webhook receiver (gasup-webhook.ts forwards here)
          - Excel parser after row normalization
        """
        dedup_key = f"{tx.estacion_id}:{tx.ticket_id}"
        if dedup_key in self._processed_tickets:
            return False

        # Clean placa
        tx.placa = tx.placa.strip().upper().replace("-", "").replace(" ", "")

        # Sobreprecio is VARIABLE — only compute if explicitly set on tx
        if tx.sobreprecio > 0 and tx.total_sobreprecio == 0:
            tx.total_sobreprecio = tx.litros * tx.sobreprecio
        elif tx.sobreprecio == 0:
            logger.debug(f"No sobreprecio for {tx.placa} ticket {tx.ticket_id} — enrich from recaudos report")

        self._transactions.append(tx)
        self._processed_tickets.add(dedup_key)
        self._update_vehicle_aggregate(tx)

        return True

    def ingest_excel_report(
        self,
        filepath: Path,
        report_type: str = "ventas_detalladas",
        estacion_id: str = "",
        estacion_nombre: str = "",
        financiera_filter: Optional[set[str]] = None,
    ) -> int:
        """
        Parse a GasUp HeadOffice Excel report and ingest transactions.

        Supports BOTH .xls (xlrd) and .xlsx (openpyxl) formats.
        GasUp exports .xls — this is the primary format.

        Calibrated column mappings (from real GasUp reports 2026-04-13):

        ventas_detalladas — headers at row 14 (0-indexed 13):
          Col 1:EDS  4:Fecha  7:Producto  10:Placa  11:#Factura
          14:MedioPago  15:Hora  16:PrecioUnit  17:Cantidad(LEQ)
          20:TotalVenta  21:RecaudoCrédito  23:RecaudoEfectivo
          24:TotalVenta+Recaudo  25:FolioFactura

        recaudos_financiera — headers at row 7 (0-indexed 6):
          Col 1:EDS  2:CodigoFactura  5:Cantidad  6:Precio
          7:Descuento  8:TotalVenta  10:Recaudo  12:FechaVenta
          15:NumeroCredito  16:Financiera  17:OrigenRecaudo

        Returns number of transactions ingested (excluding duplicates).
        """
        if not filepath.exists():
            logger.error(f"File not found: {filepath}")
            return 0

        # Dedup on file hash
        file_bytes = filepath.read_bytes()
        file_hash = hashlib.sha256(file_bytes).hexdigest()[:16]
        dedup_key = f"file:{file_hash}"
        if dedup_key in self._processed_tickets:
            logger.info(f"File already processed: {filepath.name}")
            return 0

        # Detect format and read rows
        ext = filepath.suffix.lower()
        rows_data: list[list] = []

        if ext == ".xls":
            rows_data = _read_xls(filepath)
        elif ext in (".xlsx", ".xlsm"):
            rows_data = _read_xlsx(filepath)
        else:
            # Try xlrd first (handles .xls), fall back to openpyxl
            rows_data = _read_xls(filepath)
            if not rows_data:
                rows_data = _read_xlsx(filepath)

        if not rows_data:
            logger.warning(f"Could not read any rows from {filepath.name}")
            return 0

        # Route to calibrated parser
        if report_type == "recaudos_financiera":
            count = self._parse_recaudos_financiera(rows_data, estacion_id, financiera_filter=financiera_filter)
        else:
            # Default: ventas_detalladas format
            count = self._parse_ventas_detalladas(rows_data, estacion_id, estacion_nombre)

        self._processed_tickets.add(dedup_key)
        logger.info(f"Ingested {count} transactions from {filepath.name} (type={report_type})")
        return count

    def _parse_ventas_detalladas(
        self,
        rows_data: list[list],
        estacion_id: str = "",
        estacion_nombre: str = "",
    ) -> int:
        """
        Parse ventas_detalladas with calibrated column positions.
        Headers at row 14 (index 13). Placa at col 10.
        Sobreprecio = RecaudoCrédito (col 21) + RecaudoEfectivo (col 23).
        """
        # Column positions (0-indexed) — calibrated from real report
        C_EDS = 1
        C_FECHA = 4
        C_PRODUCTO = 7
        C_PLACA = 10
        C_NUM_FACTURA = 11
        C_MEDIO_PAGO = 14
        C_HORA = 15
        C_PRECIO_UNIT = 16
        C_CANTIDAD = 17    # litros LEQ
        C_TOTAL_VENTA = 20
        C_RECAUDO_CREDITO = 21
        C_RECAUDO_EFECTIVO = 23
        C_TOTAL_VENTA_RECAUDO = 24
        HEADER_ROW = 13    # 0-indexed

        # Validate we have enough rows
        if len(rows_data) <= HEADER_ROW + 1:
            # Try auto-detecting header by looking for "Placa" in first 20 rows
            HEADER_ROW = self._find_header_row(rows_data, "placa", max_scan=20)
            if HEADER_ROW is None:
                logger.warning("ventas_detalladas: could not find header row with 'Placa'")
                return 0

        count = 0
        for i, row in enumerate(rows_data):
            if i <= HEADER_ROW:
                continue
            if len(row) <= C_PLACA:
                continue

            placa = str(row[C_PLACA] or "").strip().upper()
            if not placa or placa == "PLACA":
                continue

            litros = _safe_float(row[C_CANTIDAD] if len(row) > C_CANTIDAD else 0)
            if litros <= 0:
                continue

            precio = _safe_float(row[C_PRECIO_UNIT] if len(row) > C_PRECIO_UNIT else 0) or 13.99
            total_venta = _safe_float(row[C_TOTAL_VENTA] if len(row) > C_TOTAL_VENTA else 0)
            recaudo_cred = _safe_float(row[C_RECAUDO_CREDITO] if len(row) > C_RECAUDO_CREDITO else 0)
            recaudo_efec = _safe_float(row[C_RECAUDO_EFECTIVO] if len(row) > C_RECAUDO_EFECTIVO else 0)
            sobreprecio_total = recaudo_cred + recaudo_efec

            # Compute per-LEQ sobreprecio from this transaction
            sobreprecio_per_leq = (sobreprecio_total / litros) if litros > 0 else 0

            eds_name = str(row[C_EDS] or estacion_nombre or "").strip()
            ticket = str(row[C_NUM_FACTURA] if len(row) > C_NUM_FACTURA else f"VD-{count}").strip()

            # Parse date
            fecha_raw = row[C_FECHA] if len(row) > C_FECHA else None
            fecha = _parse_date(fecha_raw)

            medio = str(row[C_MEDIO_PAGO] if len(row) > C_MEDIO_PAGO else "efectivo").strip().lower()

            tx = GasUpTransaction(
                placa=placa,
                litros=litros,
                precio_unitario=precio,
                total=total_venta or (litros * precio),
                estacion_id=estacion_id or _eds_to_id(eds_name),
                estacion_nombre=eds_name,
                manguera=1,
                fecha_hora=fecha,
                medio_pago=medio,
                ticket_id=ticket or f"VD-{count}",
                sobreprecio=sobreprecio_per_leq,
                total_sobreprecio=sobreprecio_total,
            )

            if self.ingest_transaction(tx):
                count += 1

        return count

    def _parse_recaudos_financiera(
        self,
        rows_data: list[list],
        estacion_id: str = "",
        financiera_filter: Optional[set[str]] = None,
    ) -> int:
        """
        Parse recaudos_financiera transaccional with calibrated column positions.
        Headers at row 7 (index 6). Financiera at col 16.
        Sobreprecio = Recaudo (col 10).
        NO placa in this report — uses Codigo Factura as ticket for joining.

        Args:
            financiera_filter: Set of financiera names to include (lowercase).
                              None = process ALL financieras (for analysis).
                              Empty set = default filter (conductores/central gas).
        """
        C_EDS = 1
        C_CODIGO_FACTURA = 2
        C_CANTIDAD = 5        # litros
        C_PRECIO = 6
        C_DESCUENTO = 7
        C_TOTAL_VENTA = 8
        C_RECAUDO = 10        # actual sobreprecio amount
        C_FECHA_VENTA = 12
        C_NUMERO_CREDITO = 15
        C_FINANCIERA = 16
        C_ORIGEN_RECAUDO = 17
        HEADER_ROW = 6        # 0-indexed

        # Default filter: our financiera. None = process ALL.
        if financiera_filter is None:
            FINANCIERA_FILTER: Optional[set[str]] = None  # process all
        elif len(financiera_filter) == 0:
            FINANCIERA_FILTER = {"conductores", "central gas", "centralgas"}
        else:
            FINANCIERA_FILTER = {f.lower() for f in financiera_filter}

        if len(rows_data) <= HEADER_ROW + 1:
            HEADER_ROW = self._find_header_row(rows_data, "financiera", max_scan=15)
            if HEADER_ROW is None:
                logger.warning("recaudos_financiera: could not find header row with 'Financiera'")
                return 0

        count = 0
        total_all = 0
        for i, row in enumerate(rows_data):
            if i <= HEADER_ROW:
                continue
            if len(row) <= C_FINANCIERA:
                continue

            total_all += 1
            financiera = str(row[C_FINANCIERA] or "").strip()

            # Filter: only process our financiera's transactions
            # If FINANCIERA_FILTER is empty, process all (for analysis)
            if FINANCIERA_FILTER and financiera.lower() not in FINANCIERA_FILTER:
                continue

            litros = _safe_float(row[C_CANTIDAD] if len(row) > C_CANTIDAD else 0)
            if litros <= 0:
                continue

            recaudo = _safe_float(row[C_RECAUDO] if len(row) > C_RECAUDO else 0)
            precio = _safe_float(row[C_PRECIO] if len(row) > C_PRECIO else 0)
            total_venta = _safe_float(row[C_TOTAL_VENTA] if len(row) > C_TOTAL_VENTA else 0)
            codigo_factura = str(row[C_CODIGO_FACTURA] or "").strip()
            eds_name = str(row[C_EDS] or "").strip()
            sobreprecio_per_leq = (recaudo / litros) if litros > 0 else 0

            fecha_raw = row[C_FECHA_VENTA] if len(row) > C_FECHA_VENTA else None
            fecha = _parse_date(fecha_raw)

            num_credito = str(row[C_NUMERO_CREDITO] if len(row) > C_NUMERO_CREDITO else "").strip()

            # No placa in this report — use codigo_factura as ticket for join
            tx = GasUpTransaction(
                placa=f"RECAUDO-{codigo_factura}",  # placeholder — join with ventas for real placa
                litros=litros,
                precio_unitario=precio,
                total=total_venta,
                estacion_id=estacion_id or _eds_to_id(eds_name),
                estacion_nombre=eds_name,
                manguera=1,
                fecha_hora=fecha,
                medio_pago="credito",
                ticket_id=codigo_factura or f"RF-{count}",
                sobreprecio=sobreprecio_per_leq,
                total_sobreprecio=recaudo,
                id_cliente=num_credito,
                nombre_cliente=financiera,
            )

            if self.ingest_transaction(tx):
                count += 1

        logger.info(f"recaudos_financiera: {total_all} total rows, {count} ingested (financiera filter: {FINANCIERA_FILTER})")
        return count

    @staticmethod
    def _find_header_row(
        rows_data: list[list],
        keyword: str,
        max_scan: int = 20,
    ) -> Optional[int]:
        """Auto-detect header row by scanning for a keyword in first N rows."""
        keyword_lower = keyword.lower()
        for i, row in enumerate(rows_data[:max_scan]):
            for cell in row:
                if cell and keyword_lower in str(cell).lower():
                    return i
        return None

    # ── Vehicle Aggregation ────────────────────────────────────

    def _update_vehicle_aggregate(self, tx: GasUpTransaction) -> None:
        """Update running vehicle consumption aggregate."""
        v = self._vehicles.get(tx.placa)
        if not v:
            v = VehicleConsumption(
                placa=tx.placa,
                total_litros=0, total_cargas=0, total_mxn=0,
                total_sobreprecio=0,
            )
            self._vehicles[tx.placa] = v

        v.total_litros += tx.litros
        v.total_cargas += 1
        v.total_mxn += tx.total
        v.total_sobreprecio += tx.total_sobreprecio
        v.estaciones.add(tx.estacion_id)

        if v.primera_carga is None or tx.fecha_hora < v.primera_carga:
            v.primera_carga = tx.fecha_hora
        if v.ultima_carga is None or tx.fecha_hora > v.ultima_carga:
            v.ultima_carga = tx.fecha_hora

        v.litros_promedio_por_carga = v.total_litros / v.total_cargas if v.total_cargas > 0 else 0

        # Days since last charge
        if v.ultima_carga:
            v.dias_sin_cargar = (datetime.now() - v.ultima_carga).days

    # ── Query Interface ────────────────────────────────────────

    def get_vehicle(self, placa: str) -> VehicleConsumption | None:
        """Get consumption profile for a specific vehicle."""
        clean = placa.strip().upper().replace("-", "").replace(" ", "")
        return self._vehicles.get(clean)

    def get_all_vehicles(self) -> list[VehicleConsumption]:
        """Get all tracked vehicles, sorted by last charge date."""
        return sorted(
            self._vehicles.values(),
            key=lambda v: v.ultima_carga or datetime.min,
            reverse=True,
        )

    def get_transactions(
        self,
        placa: str | None = None,
        estacion_id: str | None = None,
        date_from: datetime | None = None,
        date_to: datetime | None = None,
        limit: int = 100,
    ) -> list[GasUpTransaction]:
        """Query transactions with optional filters."""
        result = self._transactions
        if placa:
            clean = placa.strip().upper().replace("-", "").replace(" ", "")
            result = [t for t in result if t.placa == clean]
        if estacion_id:
            result = [t for t in result if t.estacion_id == estacion_id]
        if date_from:
            result = [t for t in result if t.fecha_hora >= date_from]
        if date_to:
            result = [t for t in result if t.fecha_hora <= date_to]
        return result[-limit:]

    def get_daily_summary(
        self,
        estacion_id: str,
        fecha: str,
    ) -> DailyClose:
        """Get or compute daily close summary for a station."""
        key = f"{estacion_id}:{fecha}"
        if key in self._daily_closes:
            return self._daily_closes[key]

        # Compute from transactions
        day_txs = [
            t for t in self._transactions
            if t.estacion_id == estacion_id
            and t.fecha_hora.strftime("%Y-%m-%d") == fecha
        ]

        close = DailyClose(
            estacion_id=estacion_id,
            fecha=fecha,
            total_litros=sum(t.litros for t in day_txs),
            total_ventas_mxn=sum(t.total for t in day_txs),
            total_transacciones=len(day_txs),
        )

        # Group by medio_pago
        for t in day_txs:
            close.ventas_por_medio_pago[t.medio_pago] = (
                close.ventas_por_medio_pago.get(t.medio_pago, 0) + t.total
            )
        # Group by turno
        for t in day_txs:
            if t.turno:
                close.ventas_por_turno[t.turno] = (
                    close.ventas_por_turno.get(t.turno, 0) + t.total
                )

        close.mangueras_activas = len({t.manguera for t in day_txs})
        self._daily_closes[key] = close
        return close

    # ── Retention Engine Integration ───────────────────────────

    def check_retention(
        self,
        segment_lookup: dict[str, str] | None = None,
    ) -> list[RetentionAlert]:
        """
        Check all tracked vehicles for retention alerts.

        Args:
            segment_lookup: dict of placa → segment name (from market_loader).
                           If None, uses default 7-day threshold for all.

        Returns:
            List of RetentionAlert for vehicles needing attention.
        """
        alerts: list[RetentionAlert] = []
        now = datetime.now()

        for placa, v in self._vehicles.items():
            if not v.ultima_carga:
                continue

            # Determine segment-specific inactivity threshold
            segment = (segment_lookup or {}).get(placa, "UNKNOWN")
            threshold_days = self._inactivity_days.get(segment, 7)

            days_inactive = (now - v.ultima_carga).days

            # Alert: Inactivity
            if days_inactive >= threshold_days:
                severity = "medium"
                if days_inactive >= threshold_days * 2:
                    severity = "high"
                if days_inactive >= threshold_days * 3:
                    severity = "critical"

                alerts.append(RetentionAlert(
                    placa=placa,
                    alert_type=AlertType.INACTIVITY,
                    severity=severity,
                    message=(
                        f"{placa} ({segment}) sin cargar hace {days_inactive} días "
                        f"(umbral: {threshold_days}d). "
                        f"Última carga: {v.ultima_carga.strftime('%Y-%m-%d')}. "
                        f"Promedio: {v.litros_promedio_por_carga:.1f} LEQ/carga."
                    ),
                    data={
                        "dias_inactivo": days_inactive,
                        "umbral_dias": threshold_days,
                        "segment": segment,
                        "ultima_carga": v.ultima_carga.isoformat(),
                        "total_cargas": v.total_cargas,
                        "litros_promedio": round(v.litros_promedio_por_carga, 1),
                        "sobreprecio_acumulado": round(v.total_sobreprecio, 2),
                    },
                ))

        # Sort by severity
        severity_order = {"critical": 0, "high": 1, "medium": 2, "low": 3}
        alerts.sort(key=lambda a: severity_order.get(a.severity, 99))

        return alerts

    def get_financing_status(self, placa: str) -> dict | None:
        """
        Get financing accumulation status for a vehicle.

        Returns the total sobreprecio accumulated (GasUp recaudo that goes
        toward the vehicle purchase in cierre-mensual).
        """
        v = self.get_vehicle(placa)
        if not v:
            return None

        return {
            "placa": placa,
            "total_sobreprecio_acumulado": round(v.total_sobreprecio, 2),
            "total_litros": round(v.total_litros, 1),
            "total_cargas": v.total_cargas,
            "primera_carga": v.primera_carga.isoformat() if v.primera_carga else None,
            "ultima_carga": v.ultima_carga.isoformat() if v.ultima_carga else None,
            "dias_activo": (v.ultima_carga - v.primera_carga).days if v.primera_carga and v.ultima_carga else 0,
            "promedio_mensual_sobreprecio": _monthly_average(v),
        }

    # ── Stats ──────────────────────────────────────────────────

    def stats(self) -> dict:
        """Overall connector statistics."""
        return {
            "total_transactions": len(self._transactions),
            "total_vehicles_tracked": len(self._vehicles),
            "total_litros": round(sum(v.total_litros for v in self._vehicles.values()), 1),
            "total_revenue_mxn": round(sum(v.total_mxn for v in self._vehicles.values()), 2),
            "total_sobreprecio_mxn": round(sum(v.total_sobreprecio for v in self._vehicles.values()), 2),
            "tickets_in_dedup": len(self._processed_tickets),
        }


# ============================================================
# Helpers
# ============================================================

def _safe_float(val) -> float:
    """Safely convert a value to float, returning 0 on failure."""
    if val is None:
        return 0.0
    try:
        s = str(val).replace(",", "").replace("#N/A", "0").strip()
        return float(s) if s else 0.0
    except (ValueError, TypeError):
        return 0.0


def _read_xls(filepath: Path) -> list[list]:
    """Read .xls file using xlrd. Returns list of rows (each row = list of cell values)."""
    try:
        import xlrd
    except ImportError:
        logger.error("xlrd not installed. Run: pip install xlrd")
        return []

    try:
        wb = xlrd.open_workbook(str(filepath))
        ws = wb.sheet_by_index(0)
        rows = []
        for row_idx in range(ws.nrows):
            row = []
            for col_idx in range(ws.ncols):
                cell = ws.cell(row_idx, col_idx)
                # Handle xlrd date cells
                if cell.ctype == xlrd.XL_CELL_DATE:
                    try:
                        dt_tuple = xlrd.xldate_as_tuple(cell.value, wb.datemode)
                        row.append(datetime(*dt_tuple[:6]))
                    except Exception:
                        row.append(cell.value)
                else:
                    row.append(cell.value)
            rows.append(row)
        return rows
    except Exception as e:
        logger.debug(f"xlrd could not read {filepath.name}: {e}")
        return []


def _read_xlsx(filepath: Path) -> list[list]:
    """Read .xlsx file using openpyxl. Returns list of rows."""
    try:
        import openpyxl
    except ImportError:
        logger.error("openpyxl not installed. Run: pip install openpyxl")
        return []

    try:
        wb = openpyxl.load_workbook(filepath, read_only=True, data_only=True)
        ws = wb.active
        if not ws:
            wb.close()
            return []
        rows = []
        for row in ws.iter_rows(values_only=True):
            rows.append(list(row))
        wb.close()
        return rows
    except Exception as e:
        logger.debug(f"openpyxl could not read {filepath.name}: {e}")
        return []


def _parse_date(val) -> datetime:
    """Parse various date formats from GasUp reports."""
    if isinstance(val, datetime):
        return val
    if val is None:
        return datetime.now()
    s = str(val).strip()
    # Try common formats
    for fmt in ("%Y-%m-%d", "%d/%m/%Y", "%Y-%m-%d %H:%M:%S", "%d/%m/%Y %H:%M:%S",
                "%Y-%m-%dT%H:%M:%S", "%m/%d/%Y"):
        try:
            return datetime.strptime(s, fmt)
        except ValueError:
            continue
    try:
        return datetime.fromisoformat(s)
    except (ValueError, TypeError):
        return datetime.now()


# EDS name → station ID mapping (from real report names)
_EDS_NAME_MAP = {
    "5 de febrero": "ECG-01",
    "5 febrero": "ECG-01",
    "nacozari": "ECG-03",
    "pensión": "ECG-03",
    "pension": "ECG-03",
    "ojo caliente": "ECG-02",
    "poniente": "ECG-02",
    "oriente": "ECG-02",
    "colón": "ECG-01",
    "colon": "ECG-01",
    "parques industriales": "ECG-01",
}


def _eds_to_id(eds_name: str) -> str:
    """Map EDS name from GasUp report to our internal station ID."""
    if not eds_name:
        return "ECG-00"
    name_lower = eds_name.strip().lower()
    for key, station_id in _EDS_NAME_MAP.items():
        if key in name_lower:
            return station_id
    return "ECG-00"  # unknown station


def _monthly_average(v: VehicleConsumption) -> float:
    """Calculate monthly average sobreprecio accumulation."""
    if not v.primera_carga or not v.ultima_carga:
        return 0.0
    days = (v.ultima_carga - v.primera_carga).days
    if days <= 0:
        return v.total_sobreprecio
    months = max(days / 30.0, 1.0)
    return round(v.total_sobreprecio / months, 2)
